[tools]
lua-language-server = "latest"
stylua = "latest"
markdownlint-cli2 = "latest"
pre-commit = "latest"
oxfmt = "latest"
oxlint = "latest"

[tools.rust]
version = "stable"
components = ["clippy", "rustfmt"]
