return {
  cmd = { "oxfmt", "--lsp" },
  filetypes = {
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "json",
    "jsonc",
    "yaml",
    "html",
    "vue",
    "css",
    "scss",
    "less",
    "markdown",
  },
  root_markers = {
    ".oxfmtrc.json",
    ".oxfmtrc.jsonc",
    "oxfmt.config.ts",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "bun.lock",
    "jsconfig.json",
    "tsconfig.json",
  },
  workspace_required = true,
}
